services:
  app:
    image: olymahmudmugdho/cloud-native-contacts
    container_name: cloud-native-contacts
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/contacts_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=mysecretpassword
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
      - MAIL_HOST=${MAIL_HOST}
      - MAIL_PORT=${MAIL_PORT}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - CLOUDINARY_CLOUDNAME=${CLOUDINARY_CLOUDNAME}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
    networks:
      - contacts-network
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=contacts_db
    ports:
      - 5432:5432
    networks:
      - contacts-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 30s
networks:
  contacts-network:
    driver: bridge
    name: contacts-network