server:
  port: 8080

spring:
  application:
    name: aws-cloud-native-contacts
  
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/contacts_db}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:mysecretpassword}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME:org.postgresql.Driver}
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  
  # File Upload settings
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 10MB
      max-request-size: 10MB
  
  # Static resource handling
  web:
    resources:
      static-locations:
        - classpath:/static/
        - file:uploads/
      add-mappings: true
  mvc:
    throw-exception-if-no-handler-found: true
    static-path-pattern: /**

  
  # Email Configuration
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  
  # Allow circular references
  main:
    allow-circular-references: true

# Application specific configuration
app:
  jwt:
    secret: 5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
    expiration: 86400000 # 24 hours in milliseconds

# CORS Configuration
management:
  endpoints:
    web:
      cors:
        allowed-origins: 
          - http://localhost:3000
          - http://localhost:3001
          - ${ALLOWED_ORIGIN}
        allowed-methods:
          - GET
          - POST
          - PUT
          - DELETE
          - OPTIONS
        allowed-headers: "*"
        allow-credentials: true

# Logging configuration
logging:
  level:
    org:
      springframework:
        web: DEBUG
        web.servlet.resource: TRACE 

# Cloudinary Configuration
cloudinary:
  cloud-name: ${CLOUDINARY_CLOUDNAME} 
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}